//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Books.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Books ( [Id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
        /// [Name] TEXT, [Author] TEXT, [Price] REAL, [Year] INTEGER ).
        /// </summary>
        public static string CreateTableBook {
            get {
                return ResourceManager.GetString("CreateTableBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db3FilePathName1.
        /// </summary>
        public static string Db3FilePathName1 {
            get {
                return ResourceManager.GetString("Db3FilePathName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Books ([Id], Name, Author, Price, [Year]) VALUES 
        /// (1, &apos;Война и мир&apos;, &apos;Л.Н. Толстой&apos;, 260, 1975);
        ///INSERT INTO Books ([Id], Name, Author, Price, [Year]) VALUES
        /// (2, &apos;Отцы и дети&apos;, &apos;И. Тургенев&apos;, 180, 1979);
        ///INSERT INTO Books ([Id], Name, Author, Price, [Year]) VALUES
        /// (3, &apos;Чайка&apos;, &apos;А. Чехов&apos;, 150, 1980);
        ///INSERT INTO Books ([Id], Name, Author, Price, [Year]) VALUES
        /// (4, &apos;Когда проснётся Марс&apos;, &apos;В. Огнева&apos;, 350, 2015);
        ///INSERT INTO Books ([Id], Name, Author, Price, [Year]) VALUES
        /// (5, &apos;Крут [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertToBooks {
            get {
                return ResourceManager.GetString("InsertToBooks", resourceCulture);
            }
        }
    }
}
